DATA:
  IMG_SIZE: 256
MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_hd24_window8_256
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 8